%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: ../data

# camera intrinsics
camera.fx: 611.849
camera.fy: 612.304
camera.cx: 325.981
camera.cy: 253.49

num_features: 150
num_features_init: 50
num_features_tracking: 50
